diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.emal=millareslazaro1@gmail.com
user.name=Millares
user.email=millareslazaro1@gmail.com
alias.tree=log --graph --pretty=oneline --abbrev-commit
safe.directory=C:/Users/milla/Documents/Maestria (Tesis)/Progmramcion/Modelo Arima de la Demanda/Investigation_Code
safe.directory=C:/Users/milla/Documents/Maestria (Tesis)/Capitulo 2/Modelo Arima de la Demanda/Investigation_Code
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Millares95/Investigation_Code.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
